version: '3.8'
services:
    php:
        container_name: php
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: pasang
            MYSQL_DATABASE: assignment1
            MYSQL_USER: user1
            MYSQL_PASSWORD: user1
        ports:
            - "9906:3306"
        volumes:
            - ./database.sql:/docker-entrypoint-initdb.d/0_init.sql
    phpmyadmin:
     container_name: adminsql
     image: phpmyadmin/phpmyadmin
     ports:
       - 8080:80
     restart: always
     environment:
       PMA_HOST: db
     depends_on:
       - db